on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
name: 🚀 Deploy website on push master
jobs:
  web-deploy:
    name: 🎉 FTPS-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 100

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: access858581656.webspace-data.io
          username: u103584624
          password: ${{ secrets.IONOS_SFTP_PASSWORD_TEST }}
          # protocol: ftps
          port: 22
